pipeline {
  agent any
  
  tools {
    jdk   'openjdk-13'
    maven 'maven:3.6.3'
  }

  stages {
    stage('Initialize') {
      steps {
          echo "PATH = ${PATH}"
          echo "M2_HOME = ${M2_HOME}"
      }
    }
    stage('Build') {
      steps {
        sh 'mvn install'
      }
    }
    stage('Deploy') {
      steps {
        echo 'Deploying....'
      }
    }
  }
}
